version: "3.0"

services: 
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ".:/project"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=CAP
      - DB_USERNAME=dev
      - DB_PASSWORD=secret

  db:
    image: mysql:5.6.45
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_DATABASE=CAP
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local